<?php require_once 'layout/header.phtml' ?>

<div>
    <?php
        $n = 1;
        echo "Genero " . $serie->genero . '</br>';
            echo "Cant temporadas " . $serie->cant_temporadas . '</br>';
            echo "Sinopsis " . $serie->sinopsis . '</br>';
            echo "Clasificacion +" . $serie->clasificación . '</br>';
        foreach ($temporadas as $temporada) {
            echo "Temporada N° <a href='temporadas/$temporada->id_temporada'>".$n."</a></br>";
            $n++;   
        }
    ?>
    <a href="list_series">VOLVER</a>
</div>

<?php require_once 'layout/footer.phtml' ?>
