<?php require_once 'layout/header.phtml' ?>

<div>
    <section class="editOrDelete">
    <h4>Editar o Eliminar una temporada</h4>
    <table>
        <tr>
            <td>SERIE QUE PERTENECE</td>
            <td>num_temporada</td>
            <td>cant_capitulos</td>
            <td>ACCION 1</td>
            <td>ACCION 2</td>
        </tr>
        <?php foreach ($temporadas as $temporada): ?> 
            <tr>
            
            <?php foreach ($series as $serie): ?>
            <?php if ($serie->id_serie === $temporada->id_serie): ?>
            <td><?=$serie->titulo?></td>
            <?php endif;?>
            <?php endforeach;?>
            <td><?= $temporada->num_temporada;?></td>
            <td><?= $temporada->cant_capitulos;?></td>
            <td><a href="editTemporada/<?= $temporada->id_temporada?>">EDITAR</a></td>
            <td><a href="deleteTemporada/<?=$temporada->id_temporada?>">ELIMINAR</a></td>
            </tr>
        <?php endforeach; ?>
    </table>
    </section>
    <section class="add_temporada">
    <h4>Añadir una nueva temporada</h4>
    <form action="addTemporada" method="post">
        <select name="name">
            <?php foreach($series as $serie):?>
            <option value=<?=$serie->titulo?>><?=$serie->titulo?></option>
            <?php endforeach; ?>
        </select></br>
        <label>Numero de temporada</label>
        <input type="text" name="num_temporada"></br>    
        <label>Cantidad de capitulos</label>
        <input type="text" name="cant_capitulos"></br>
        <button type="submit">AGREGAR</button>
    </form>
</section>
</div>

<?php require_once 'layout/footer.phtml' ?>