<?php require_once 'layout/header.phtml' ?>

<div>
    <table>
        <tr>
            <td>SERIE</td>
            <td>NUM_TEMPORADA</td>
            <td>CANT_CAP</td>
            <td>RESUMEN</td>
            <td>ACCION</td>
        </tr>
        <?php foreach ($temporadas as $temporada):?>
        <tr>
            <?php foreach ($series as $serie): ?>
            <?php if ($serie->id_serie === $temporada->id_serie): ?>
            <td><?=$serie->titulo?></td>
            <?php endif;?>
            <?php endforeach;?>
            <td><?=$temporada->num_temporada?></td>
            <td><?=$temporada->cant_capitulos?></td>
            <td><?=$temporada->resumen?></td>
            <td><a href='temporadas/<?=$temporada->id_temporada?>'>Ver Detalle</a></td> 
            <?php $n++;?>
        </tr>
            <?php endforeach; ?>
    </table>
    
    <a href="home">VOLVER</a>
</div>

<?php require_once 'layout/footer.phtml' ?>