<?php require_once 'layout/header.phtml' ?>

<div>
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">SERIE</th>
            <th scope="col">NUM_TEMPORADA</th>
            <th scope="col">CANT_CAP</th>
            <th scope="col">RESUMEN</th>
            <th scope="col">ACCION</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($temporadas as $temporada):?>
        <tr>
            <?php foreach ($series as $serie): ?>
            <?php if ($serie->id_serie === $temporada->id_serie): ?>
            <td><?=$serie->titulo?></td>
            <?php endif;?>
            <?php endforeach;?>
            <td><?=$temporada->num_temporada?></td>
            <td><?=$temporada->cant_capitulos?></td>
            <td><?=$temporada->resumen?></td>
            <td><a href='temporadas/<?=$temporada->id_temporada?>'>Ver Detalle</a></td> 
            <?php $n++;?>
        </tr>
            <?php endforeach; ?>
            </tbody>
    </table>
    
    <a href="home">VOLVER</a>
</div>

<?php require_once 'layout/footer.phtml' ?>