<?php

class SeriesView {
/*     function __construct(){
    este constructor puede dejarse implicito porque php lo
    hara por nosotros dado que el mismo esta vacio.
    }
 */
    function showSeries($series, $error, $user){
        require_once '././templates/series_list.phtml';
    }

    function showSerieByID($serie,$temporadas, $error, $user){
        require_once '././templates/lista_temporadas.phtml';
    }

    function showSeriebyGenre($serie, $error, $user){
        require_once '././templates/serie_by_genre.phtml';
    }

    function showError($error){
        echo "<h3>$error</h3>";
    }
}