<?php
    class TemporadasView {
        function showTemporadas($temporadas,$serie){
            require_once '././templates/lista_temporadas.phtml';
        }
        
        function showAllTemporadas($temporadas){
            require_once '././templates/temporadas.phtml';
        }

        function showTemporadaByID($temporada){
            require_once '././templates/temporada.phtml';
        }
    }
?>  