<?php
    class TemporadasView {
        function showTemporadas($temporadas,$serie, $error, $user){
            require_once '././templates/lista_temporadas.phtml';
        }
        
        function showAllTemporadas($temporadas, $error, $user){
            require_once '././templates/temporadas.phtml';
        }

        function showTemporadaByID($temporada, $error, $user){
            require_once '././templates/temporada.phtml';
        }
        function showTemporadasABM($temporadas,$error,$user){
            require_once '././templates/panel_temporadas.phtml';
        }
            public function showError($error, $user) {
        echo "<h1>$error</h1>";
    }

    }
?>  