<?php require_once 'header.phtml'?>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <!-- con php jej -->
        <img src="https://www.mundiario.com/asset/thumbnail,1280,720,center,center/media/cineseries/images/2025/08/19/2025081918014991689.webp" alt="Image">
        <div class="carousel-caption">
          <h3>SERIE A</h3>
          <p>GENERO?</p>
        </div>      
      </div>

      <div class="item">
        <img src="https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/27b24f5b-de78-4f68-b04a-e4e6746e543f/compose?aspectRatio=1.78&format=webp&width=1200" alt="Image">
        <div class="carousel-caption">
          <h3>SERIE B</h3>
          <p>GENERO??</p>
        </div>      
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>

<?php require_once 'footer.phtml'?>