<?php require_once 'header.php'?>

<div>
    <h1>Watchy</h1>
    <p>Watchy es una plataforma dedicada a los amantes de las series. Descubrí, explorá y seguí tus programas favoritos con información detallada, recomendaciones personalizadas y las últimas novedades del mundo del entretenimiento. ¡Todo lo que necesitás para disfrutar tus series en un solo lugar!</p>
        <a href="series">Ver Series</a>

</div>

<?php require_once 'footer.php'?>