<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--<link rel="stylesheet" href="././css/styles.css">-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <base href="<?php echo BASE_URL ?>">
    <title>Watchy</title>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="home">WATCHY</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="home">Home</a></li>
        <li><a href="list_series">Series</a></li>
        <li><a href="temporadas">Temporadas</a></li>
        <li><a href="about">About</a></li>
        <?php if (!empty($user)): ?>
            <li><a href="panel_admin">Admin</a></li>
        <?php endif; ?>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <?php if (!empty($user)): ?>
            <li><a href="logout"><span class="glyphicon glyphicon-log-out"></span> LOGOUT</a></li>
        <?php else: ?>
            <li><a href="login"><span class="glyphicon glyphicon-log-in"></span> LOGIN</a></li>
        <?php endif; ?>
      </ul>
    </div>
  </div>
</nav>
