<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?php echo BASE_URL ?>">
    <title>Watchy</title>
</head>
<body>
    <header>
        <h1>WATCHY</h1>
        <?php if ($user): ?>
            <a href="logout">LOGOUT</a>
        <?php else: ?>
            <a href="login">LOGIN</a>
        <?php endif; ?>
    </header>